### ISSUE TITLE
issue tracker labels for data repository

### ISSUE THREAD

**Issue by mianzg** [openwashdata-dev/book#27]
In `data` repository, each data submission issue should be examined by the team and later assigned with labels to better visualise its type and efforts required. I suggest the following ones:

By difficulty:
- easy: we can release a version within 2 weeks, e.g., small data with clear description
- medium: we can release a version within 2 months
- hard: we need to invest more than 2 months 

By feature request:
- dict-needed: the data request did not have a dictionary file to explain variables
- author-needed: detailed author metadata (e.g., ORCID) is missing

By source:
- academic
- public-sector
- other

@larnsce @sebastian-loos let's finalise some and add into the repository.

**Comment by larnsce** [comment]
Thanks, @mianzg, for setting these up.

I like the difficulty label, but would actually change it to: days, weeks, months. I don't think we need the feature request label for now. The source label would make great variable in a metadata table, but again I don't think we need it for the issue tracker. I have started a metadata table to document each data package:

https://docs.google.com/spreadsheets/d/1vtw16vpvJbioDirGTQcy0Ubz01Cz7lcwFVvbxsNPSVM/edit#gid=0

The corresponding attributes (dictionary) is here:

https://docs.google.com/spreadsheets/d/1nn2jkhCGKyO5o9KmjQuSNPxm4fPK-ZqVb7uP0GlgaSc/edit#gid=0

One label that I would like is "value", which could justify investing time into a dataset that's labelled as "hard" but with "high" value. The problem here is that it may look like we don't see data as valuable, which would be a problem to people who submit data. So maybe we include this in our metadata table, but not actually as a label on GitHub.

**Comment by mianzg** [comment]
I feel "days, weeks, months" can give me wrong estimation since we have waiting time to get response from collaborators. 

How about using these labels for difficulty? `tidiness: low`, `tidiness: mid`, `tidiness: high`

**Comment by mianzg** [comment]
About the value thing, if we only want to label something "hard" but "high" value, I would suggest use emoji ⛏️⛏️ as a label. (need to dig out good stuff with much effort)

**Comment by larnsce** [comment]
I like the labels you have applied now and would use the corresponding categories for the metadata tables variable "difficulty" about each data package. https://docs.google.com/spreadsheets/d/1vtw16vpvJbioDirGTQcy0Ubz01Cz7lcwFVvbxsNPSVM/edit#gid=0
